// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "hAESWFY5PagkZ16MtbQtgZoNVh5o1jo7P0pADRLdmXyNqmzn6XfLHVs4AQ5Lkkr6AUcBjv";
}
}
}

