// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "tIcRudwAtFrFE6QgHucowuuVqX7nGTi3UMCWxywWV2DXxnruyvomIPcDPcTwiFoyo7BLu9";
}
}
}

