// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "85sMAeTylTZNgBTMtrA20kYTwoermWe1MGkoSsVOTf4Ymh12Ovc31kB5ToVKu5gVHR24Ia";
}
}
}

