// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "4vCVwgBslxI82yCS9AGQjA9GZmWNEcZ9JOKUkafUioNk94WWj6ALaXcVqL8T8bnlwPMI1i";
}
}
}

